pipeline:
  name: ang_ci_dev2
  identifier: ang_ci_dev2
  projectIdentifier: Harness_Migration_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: angular_firebase_connector
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: compile
        identifier: compile
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: Docker_connector
                    image: node:12.12.0-alpine
                    shell: Sh
                    command: |-
                      echo 'test'
                      npm install -g @angular/cli
                      npm install
  delegateSelectors:
    - harness-gcp-delegate
