pipeline:
  name: ang_ci_dev2
  identifier: ang_ci_dev2
  projectIdentifier: Harness_Migration_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: angular_git_connector
        build: <+input>
  stages:
    - stage:
        name: compile
        identifier: compile
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    shell: Sh
                    command: echo 'test'
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: GAR_Connector
                    host: asia-south1
                    projectID: global-grammar-475407-a7/angularcli
                    imageName: angular_firebase
                    tags:
                      - "1.0"
